language: python

matrix:
    include:
      - python: "2.7"
        os: linux
      - python: "3.2"
        os: linux
      - python: "3.3"
        os: linux
      - python: "3.4"
        os: linux
      - python: "3.5"
        os: linux
      - os: osx
        language: generic

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
     then sudo pip install cram;
     else      pip install cram; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then sudo python setup.py install;
      else      python setup.py install; fi

script:
    - cram --indent=4 test.cram
